apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: arachne-brokers
  namespace: kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
