apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: NodePort
  selector:
    app: scraper-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32734
