apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service-deployment
  labels:
    app: scraper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-service
  template:
    metadata:
      labels:
        app: scraper-service
    spec:
      containers:
        - name: scraper-service
          image: arachne.azurecr.io/scraper-service:0.1
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret
